#!/usr/local/munkireport/munkireport-python3

import subprocess
import os
import sys
import platform
from datetime import datetime

from Foundation import CFPreferencesCopyAppValue

def get_pref_value(key, domain):
    value = CFPreferencesCopyAppValue(key, domain)
    if(value is not None):
        return value
    elif(value is not None and len(value) == 0):
        return ""
    else:
        return ""

def systemsetup(command):
    cmd = ["/usr/sbin/systemsetup", "-%s" % command ] 
    output = subprocess.check_output(cmd) 
    output = output.decode().split(':')
    setting = output[1].strip()
    return setting

def read_defaults(domain, key):
    cmd = ["/usr/bin/defaults", "read", domain, key ]
    try:
        proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                                stdin=subprocess.PIPE,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        (output, unused_error) = proc.communicate()
        output = output.decode().strip()
        return output
    except subprocess.CalledProcessError:
        return ""

def main():
    """Main"""

    timezone = systemsetup('gettimezone')
    networktime_status = bool(systemsetup('getusingnetworktime'))
    networktime_server = []
    with open('/etc/ntp.conf', 'r') as reader:
        for line in reader.readlines():
            networktime_server.append(line.split()[1])
    networktime_server = (', '.join(networktime_server))
    autotimezone = bool(get_pref_value('Active', 'com.apple.timezone.auto'))

    # Check if we're setting the preferences by profile or not
    if os.path.isfile("/Library/Managed Preferences/com.apple.timed.plist"):

        # Make sure TMAutomaticTimeOnlyEnabled is actually set
        automatic_time_only_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeOnlyEnabled")
        if automatic_time_only_enabled != "1" and TMAutomaticTimeOnlyEnabled != "0":
            automatic_time_only_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeOnlyEnabled")

        # Make sure TMAutomaticTimeZoneEnabled is actually set
        automatic_time_zone_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeZoneEnabled")
        if automatic_time_zone_enabled != "1" and automatic_time_zone_enabled != "0":
            automatic_time_zone_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeZoneEnabled")
    else:
        automatic_time_only_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeOnlyEnabled")
        automatic_time_zone_enabled = read_defaults("/private/var/db/timed/Library/Preferences/com.apple.timed.plist", "TMAutomaticTimeZoneEnabled")

    # Get current local time
    cur_local_time = datetime.now().strftime("%H:%M:%S")

    # Get location services enabled status
    location_enabled = read_defaults("/var/db/locationd/Library/Preferences/ByHost/com.apple.locationd", "LocationServicesEnabled")

    # Write memory results to cache
    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    output_file = os.path.join(cachedir, 'time.txt')
    separator = "="
    with open(output_file, "w") as f:
        f.write("timezone %s %s\n" % (separator, timezone))
        f.write("networktime_status %s %s\n" % (separator, int(networktime_status)))
        f.write("networktime_server %s %s\n" % (separator, networktime_server))
        f.write("autotimezone %s %s\n" % (separator, int(autotimezone)))
        f.write("cur_local_time %s %s\n" % (separator, cur_local_time))
        f.write("location_enabled %s %s\n" % (separator, location_enabled))
        f.write("automatic_time_only_enabled %s %s\n" % (separator, automatic_time_only_enabled))
        f.write("automatic_time_zone_enabled %s %s\n" % (separator, automatic_time_zone_enabled))
        f.close()

if __name__ == "__main__":
    main()
